# Generated by Django 3.0 on 2019-12-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('odert_ype', models.CharField(max_length=32, null=True)),
                ('order_id', models.CharField(max_length=32, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=32, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('sku', models.CharField(max_length=32, null=True)),
                ('sku_qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sku_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_stats', models.CharField(max_length=32, null=True)),
                ('delivery_comp', models.CharField(max_length=32, null=True)),
                ('delivery_numb', models.CharField(max_length=32, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('order_date', models.CharField(max_length=32, null=True)),
                ('delivery_date', models.CharField(max_length=32, null=True)),
                ('touch_date', models.CharField(max_length=32, null=True)),
                ('displace_old', models.CharField(max_length=32, null=True)),
                ('displace_oldnum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('displace_delivery', models.CharField(max_length=32, null=True)),
                ('displace_new', models.CharField(max_length=32, null=True)),
                ('displace_newnum', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
